@startuml

title "PlaceOrder"

actor "User" 

participant "Menu"
participant "Cart"
participant "Delivery Details" as DD
participant "Payment Gateway" as PG
participant "Order Confirmation" as OC

autonumber

User -> Menu: Select the needed item
Menu -> Cart: The selected item is added to the Cart
Cart -> User: The selected item is shown with its price
Cart -> User: Display the coupons, if the user has..
User -> Cart: Claim the coupon
Cart -> User: The selected item is shown with reduced price
User -> DD: Enter the Address
DD -> User: After adding address, click Place Order
PG -> User: Choose Debit/Credit card payment
PG -> User: Opens a window to enter the card details
User -> PG: Enter Debit/Credit Card Number
User -> PG: Enter the card holder name
User -> PG: Enter the CVV number
PG -> User: Sends OTP to the respective Mobile number
User -> PG: Enter the received OTP
PG -> OC: After payment is done, the order gets confirmed
OC -> User: Receives a thumbs-up icon on user's screen for order confirmation
OC -> User: Shows the expected date of delivery

@enduml