@startuml name

title Online Shopping System

skinparam ClassAttributeIconSize 0

class Customer{
    +CustomerID : int
    +Name : String
    +Email : String
    -Password : String
    -Address : String
    -Register() : void
    +login() : void
    +updateProfile() : void
}

class User {
    -userID : int
    -pwd : String
    -loginStatus : String
    +verifyLogin() : bool
}

class Administrator {
    -adminName : String
    -email : String
    +updateCatalog() : bool
}

class ShoppingCart {
    -cartID : int
    -productID : int
    -quantity : int
    -dateAdded : int
    +addCartItem() : void
    +updateQuantity() : bool
    +checkOut() : void
}

class Orders{
    -orderID : int
    -dateCreated : int
    -dateShipped : int
    -customerName : String
    -status : string
    +placeOrder() : bool
}

class OrderDetails {
    -orderID : int
    -productID : int
    -productName: String
    -quantity : int
    +calcPrice() : void
}

class ShippingInfo{
    -shippingID : int
    -shippingType : String
    +updateShippingInfo() : bool
}

User "1...*" <|-- "1" Customer : Contains
User "1...*" <|-- "1" Administrator : contains
Customer "1" <.. "1" ShoppingCart : has a
Customer "0...*" -- "1" Orders 
Orders "1" <.. "1" ShippingInfo
Orders "1" <.. "1" OrderDetails

@enduml